#!/bin/bash
# =============================================================================
# new-project.sh
# Interactive project initializer — sets up ai-rules and basic project structure
#
# Usage: ./new-project.sh
# =============================================================================

RULES_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🚀 AI Rules — New Project Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ─── Preset vs. manual selection ──────────────────────────────────────────────
echo ""
echo "Setup mode:"
echo "  1) Use a preset          (recommended for common project types)"
echo "  2) Manual selection      (pick base overlay + snippets yourself)"
echo ""
read -rp "Choice [1-2]: " mode_choice

if [[ "$mode_choice" == "1" ]]; then
  # ─── Preset selection ─────────────────────────────────────────────────────
  echo ""
  echo "Available presets:"
  PRESET_FILES=("$RULES_DIR/presets"/*.txt)
  for i in "${!PRESET_FILES[@]}"; do
    name=$(basename "${PRESET_FILES[$i]}" .txt)
    content=$(grep -v '^#' "${PRESET_FILES[$i]}" | grep -v '^$' | head -1)
    echo "  $((i+1))) $name  →  $content"
  done
  echo ""
  read -rp "Preset [1-${#PRESET_FILES[@]}]: " preset_choice

  idx=$((preset_choice-1))
  if [[ $idx -ge 0 && $idx -lt ${#PRESET_FILES[@]} ]]; then
    PRESET_NAME=$(basename "${PRESET_FILES[$idx]}" .txt)
  else
    echo "❌ Invalid choice"; exit 1
  fi

  # Read preset args
  PRESET_ARGS=$(grep -v '^#' "$RULES_DIR/presets/$PRESET_NAME.txt" | grep -v '^$' | head -1)
  read -ra PRESET_PARTS <<< "$PRESET_ARGS"
  PROJECT_TYPE="${PRESET_PARTS[0]}"
  SNIPPETS=("${PRESET_PARTS[@]:1}")

  echo ""
  echo "📦 Preset '$PRESET_NAME' → base: $PROJECT_TYPE, snippets: ${SNIPPETS[*]}"

else
  # ─── Project type selection ───────────────────────────────────────────────
  echo ""
  echo "Select project type:"
  echo "  1) ds-ml          Data Science / ML"
  echo "  2) llm-eng        LLM / GenAI Engineering"
  echo "  3) data-eng       Data Engineering"
  echo "  4) software-eng   Traditional Software Engineering"
  echo "  5) research       Research / Academic"
  echo "  6) core           Core rules only"
  echo ""
  read -rp "Choice [1-6]: " type_choice

  case $type_choice in
    1) PROJECT_TYPE="ds-ml" ;;
    2) PROJECT_TYPE="llm-eng" ;;
    3) PROJECT_TYPE="data-eng" ;;
    4) PROJECT_TYPE="software-eng" ;;
    5) PROJECT_TYPE="research" ;;
    6) PROJECT_TYPE="" ;;
    *) echo "❌ Invalid choice"; exit 1 ;;
  esac

  # ─── Snippet selection ──────────────────────────────────────────────────────
  echo ""
  echo "Select snippets to include (space-separated numbers, or Enter to skip):"
  SNIPPET_FILES=("$RULES_DIR/snippets"/*.md)
  for i in "${!SNIPPET_FILES[@]}"; do
    echo "  $((i+1))) $(basename "${SNIPPET_FILES[$i]}" .md)"
  done
  echo ""
  read -rp "Snippets: " snippet_input

  SNIPPETS=()
  for num in $snippet_input; do
    idx=$((num-1))
    if [[ $idx -ge 0 && $idx -lt ${#SNIPPET_FILES[@]} ]]; then
      SNIPPETS+=("$(basename "${SNIPPET_FILES[$idx]}" .md)")
    fi
  done
fi

# ─── Scaffold preference ─────────────────────────────────────────────────────
SCAFFOLD=false
TEMPLATE_TYPE="${PROJECT_TYPE:-ds-ml}"
if [[ -f "$RULES_DIR/templates/$TEMPLATE_TYPE.txt" ]]; then
  echo ""
  read -rp "Create project directory scaffold for '$TEMPLATE_TYPE'? (y/N): " scaffold_choice
  if [[ "$scaffold_choice" =~ ^[Yy]$ ]]; then
    SCAFFOLD=true
  fi
fi

# ─── .gitignore preference ───────────────────────────────────────────────────
echo ""
read -rp "Add generated rule files to .gitignore? (y/N): " gitignore_choice

# ─── Run sync ────────────────────────────────────────────────────────────────
echo ""
"$RULES_DIR/sync.sh" "$PROJECT_TYPE" "${SNIPPETS[@]}"

# ─── Create scaffold ─────────────────────────────────────────────────────────
if [[ "$SCAFFOLD" == true ]]; then
  echo ""
  echo "📁 Creating project scaffold..."
  while IFS= read -r line; do
    line=$(echo "$line" | xargs)  # trim whitespace
    [[ -z "$line" || "$line" == \#* || "$line" == "dirs:" ]] && continue
    [[ "$line" == "- "* ]] && line="${line#- }"
    if [[ -n "$line" ]]; then
      mkdir -p "$line"
      echo "   ✓ $line/"
    fi
  done < "$RULES_DIR/templates/$TEMPLATE_TYPE.txt"
fi

# ─── Optional .gitignore update ──────────────────────────────────────────────
if [[ "$gitignore_choice" =~ ^[Yy]$ ]]; then
  {
    echo ""
    echo "# AI rule files (generated by ai-rules/sync.sh)"
    echo "CLAUDE.md"
    echo "AGENTS.md"
    echo ".github/copilot-instructions.md"
    echo ".gemini/"
  } >> .gitignore
  echo "📝 Added rule files to .gitignore"
fi

# ─── Generate .ai-rules.yaml ─────────────────────────────────────────────────
echo ""
read -rp "Save config to .ai-rules.yaml for future sync? (Y/n): " save_config
if [[ ! "$save_config" =~ ^[Nn]$ ]]; then
  {
    echo "# .ai-rules.yaml — auto-generated by new-project.sh"
    echo "profile: ${PROJECT_TYPE:-core}"
    echo "snippets:"
    for s in "${SNIPPETS[@]}"; do
      echo "  - $s"
    done
  } > .ai-rules.yaml
  echo "📝 Saved .ai-rules.yaml — run sync.sh with no args to re-sync"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ Project initialized!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Useful commands:"
echo "  $RULES_DIR/sync.sh                    # re-sync from .ai-rules.yaml"
echo "  $RULES_DIR/sync.sh --validate          # check project against rules"
echo "  $RULES_DIR/sync.sh --list              # see all available options"
echo ""
